"""
ai/rl/trading_env.py
=====================
OptionAlpha Agent — Custom Gymnasium Trading Environment

This is the self-developed reinforcement learning environment.
The RL agent (PPO) learns to make options trading decisions by
interacting with a simulated Alpaca paper account using real
historical data replayed in sequence.

State Space (observation):
  - Account state: equity, daily P&L, open positions, portfolio delta
  - Per-symbol features: 13-dim feature vector (from FeatureMatrix)
  - Current regime: 4-dim one-hot
  - Option chain summary: ATM iv, iv_rank, bid_ask_spread
  - Position flags: 7-dim (one per universe symbol) — 0=none, 1=CSP open, 2=CC open
  Total: ~100-dim continuous observation

Action Space (Discrete):
  For each symbol in the universe (7 symbols), agent can choose:
    0: Do Nothing
    1: Open Wheel CSP (sell cash-secured put)
    2: Open Iron Condor
    3: Close Position (take profit / stop loss)
  → Total actions: 7 symbols × 4 = 28 (but pruned by legal action mask)

Reward:
  - Primary: daily P&L delta (scaled by starting capital)
  - Bonus: +0.01 per day theta decay collected
  - Penalty: -0.05 for each risk gate violation attempted
  - Episode terminal: equity drops below 50% starting capital OR 252 days elapsed

Design principles:
  - No external APIs in the environment (uses cached historical data)
  - Realistic slippage model (0.5% of bid-ask spread)
  - Realistic fill probability (limit orders may not fill)
  - Episode reset samples a random start date from historical data
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

try:
    import gymnasium as gym
    from gymnasium import spaces
    _GYM_BASE = gym.Env
except ImportError:
    class _MockSpace:
        def __init__(self, *args, **kwargs): pass
        def contains(self, x): return True
        def sample(self): return 0
    class _MockSpaces:
        Box = _MockSpace
        Discrete = _MockSpace
    spaces = _MockSpaces()
    class _GymEnv:
        metadata = {}
        def __init__(self): pass
    _GYM_BASE = _GymEnv

from config.settings import get_strategy_settings

SETTINGS = get_strategy_settings()

N_SYMBOLS    = len(SETTINGS.trading_universe)   # 7
N_ACTIONS_PER_SYMBOL = 4                        # 0=hold, 1=CSP, 2=IC, 3=close
N_ACTIONS    = N_SYMBOLS * N_ACTIONS_PER_SYMBOL

FEATURE_DIM  = 13     # per-symbol feature vector
N_REGIMES    = 4
OBS_DIM      = (
    4                          # account: equity_norm, daily_pnl_norm, n_positions, delta_norm
    + N_SYMBOLS * FEATURE_DIM  # symbol features
    + N_REGIMES                # regime one-hot
    + N_SYMBOLS * 3            # option chain: iv, iv_rank, bid_ask per symbol
    + N_SYMBOLS                # position flags
)

STARTING_CAPITAL   = SETTINGS.starting_capital
MAX_EPISODE_DAYS   = 252
TERMINAL_EQUITY    = STARTING_CAPITAL * 0.50
SLIPPAGE_PCT       = 0.005   # 0.5% of bid-ask spread


class OptionsPortfolioEnv(_GYM_BASE):
    """
    Custom Gymnasium environment for options portfolio management.
    Trained offline on historical data. Used only for RL training.
    At inference time, the trained PPO agent interfaces with the live
    Alpaca client instead.
    """

    metadata = {"render_modes": ["human", "ansi"]}

    def __init__(
        self,
        data_dir:     Path    = Path("data/cache"),
        render_mode:  str     = "ansi",
        risk_free_rate: float = 0.05,
    ):
        super().__init__()
        self.data_dir       = Path(data_dir)
        self.render_mode    = render_mode
        self.risk_free_rate = risk_free_rate

        # Spaces
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf,
            shape=(OBS_DIM,), dtype=np.float32
        )
        self.action_space = spaces.Discrete(N_ACTIONS)

        # Internal state
        self._episode_data:  Optional[Dict] = None
        self._day:           int  = 0
        self._equity:        float = STARTING_CAPITAL
        self._daily_pnl:     float = 0.0
        self._positions:     Dict[str, Dict] = {}   # symbol → position dict
        self._history:       list = []

        # Load cached historical data (generated by DataCollector)
        self._all_data = self._load_cache()

    # ─────────────────────────────────────────────────────────
    # Data loading
    # ─────────────────────────────────────────────────────────
    def _load_cache(self) -> list:
        """Load pre-fetched historical feature matrices from disk."""
        cache_file = self.data_dir / "historical_features.json"
        if not cache_file.exists():
            # Return minimal dummy data so the env can still be constructed
            return self._generate_synthetic_data()
        with open(cache_file) as f:
            return json.load(f)

    def _generate_synthetic_data(self) -> list:
        """
        Synthetic data fallback — GBM paths for each symbol.
        Used for testing and initial RL warm-up before real data arrives.
        """
        rng = np.random.default_rng(42)
        episodes = []
        for _ in range(50):  # 50 synthetic episodes
            ep = []
            prices = {sym: 400.0 + rng.uniform(-100, 200)
                      for sym in SETTINGS.trading_universe}
            iv_base = {sym: 0.20 + rng.uniform(0, 0.15)
                       for sym in SETTINGS.trading_universe}
            for day in range(MAX_EPISODE_DAYS):
                day_data = {}
                for sym in SETTINGS.trading_universe:
                    ret     = rng.normal(0.0004, iv_base[sym] / np.sqrt(252))
                    prices[sym] *= np.exp(ret)
                    iv      = iv_base[sym] * (1.0 + rng.uniform(-0.05, 0.05))
                    iv_rank = float(rng.uniform(0, 100))
                    features = [
                        ret, ret * 2, ret * 5,           # momentum
                        rng.uniform(-0.02, 0.02),        # sma_r20
                        rng.uniform(-0.03, 0.03),        # sma_r50
                        iv,                              # rv20
                        iv, iv_rank,                     # iv, iv_rank
                        rng.uniform(-0.35, 0.35),        # avg_delta
                        rng.uniform(0.01, 0.08),         # avg_gamma
                        rng.uniform(-0.05, -0.001),      # avg_theta
                        rng.uniform(0.1, 0.5),           # avg_vega
                        rng.uniform(0.5, 2.0),           # vol_ratio
                    ]
                    day_data[sym] = {
                        "features":   features,
                        "price":      prices[sym],
                        "iv":         iv,
                        "iv_rank":    iv_rank,
                        "bid_ask":    0.05 + rng.uniform(0, 0.10),
                        "atm_premium": prices[sym] * iv * np.sqrt(30 / 365) * 0.4,
                    }
                ep.append(day_data)
            episodes.append(ep)
        return episodes

    # ─────────────────────────────────────────────────────────
    # Gymnasium interface
    # ─────────────────────────────────────────────────────────
    def reset(self, *, seed=None, options=None) -> Tuple[np.ndarray, Dict]:
        super().reset(seed=seed)
        self._episode_data = self._all_data[self.np_random.integers(0, len(self._all_data))]
        self._day         = 0
        self._equity      = float(STARTING_CAPITAL)
        self._daily_pnl   = 0.0
        self._positions   = {}
        self._history     = []
        return self._get_obs(), {}

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, bool, Dict]:
        assert self._episode_data is not None
        day_data   = self._episode_data[min(self._day, len(self._episode_data) - 1)]
        reward     = 0.0
        terminated = False
        truncated  = False
        info: Dict[str, Any] = {}

        # Decode action
        symbol_idx  = action // N_ACTIONS_PER_SYMBOL
        action_type = action  % N_ACTIONS_PER_SYMBOL
        symbol      = SETTINGS.trading_universe[symbol_idx % N_SYMBOLS]
        sym_data    = day_data.get(symbol, {})

        # Execute action
        if action_type == 1:   # Open CSP
            reward += self._open_csp(symbol, sym_data)
        elif action_type == 2: # Open IC
            reward += self._open_iron_condor(symbol, sym_data)
        elif action_type == 3: # Close
            reward += self._close_position(symbol, sym_data)
        # action_type == 0: do nothing

        # Advance time — simulate theta decay on all open positions
        theta_income = self._accrue_theta(day_data)
        reward += theta_income / STARTING_CAPITAL

        # Daily P&L
        self._daily_pnl = self._equity - STARTING_CAPITAL
        reward += (self._equity - STARTING_CAPITAL) / STARTING_CAPITAL * 0.1

        self._day   += 1
        terminated   = (self._equity <= TERMINAL_EQUITY)
        truncated    = (self._day >= MAX_EPISODE_DAYS)

        info = {
            "equity":   self._equity,
            "day_pnl":  self._daily_pnl,
            "positions": len(self._positions),
        }
        return self._get_obs(), float(reward), terminated, truncated, info

    # ─────────────────────────────────────────────────────────
    # Action implementations
    # ─────────────────────────────────────────────────────────
    def _open_csp(self, symbol: str, data: Dict) -> float:
        if symbol in self._positions or len(self._positions) >= SETTINGS.max_open_positions:
            return -0.005   # penalty for illegal action
        premium = data.get("atm_premium", 5.0) * (1.0 - SLIPPAGE_PCT)
        self._positions[symbol] = {
            "type":         "CSP",
            "premium_rcvd": premium,
            "days_open":    0,
            "max_profit":   premium,
        }
        self._equity += premium   # receive credit
        return premium / STARTING_CAPITAL

    def _open_iron_condor(self, symbol: str, data: Dict) -> float:
        if data.get("iv_rank", 0) < SETTINGS.ic_min_iv_rank:
            return -0.003   # penalty: IV Rank too low for IC
        if symbol in self._positions or len(self._positions) >= SETTINGS.max_open_positions:
            return -0.005
        premium = data.get("atm_premium", 5.0) * 0.6 * (1.0 - SLIPPAGE_PCT)
        self._positions[symbol] = {
            "type":         "IC",
            "premium_rcvd": premium,
            "days_open":    0,
            "max_profit":   premium,
        }
        self._equity += premium
        return premium / STARTING_CAPITAL

    def _close_position(self, symbol: str, data: Dict) -> float:
        if symbol not in self._positions:
            return -0.001   # tiny penalty for no-op close
        pos    = self._positions.pop(symbol)
        days   = pos["days_open"]
        # Simple P&L model: remaining value decays with time
        remaining = pos["premium_rcvd"] * max(0, 1.0 - days / 45.0)
        pnl    = pos["premium_rcvd"] - remaining   # profit already collected via decay
        return pnl / STARTING_CAPITAL

    def _accrue_theta(self, day_data: Dict) -> float:
        """Simulate daily theta decay on all open positions."""
        theta_total = 0.0
        for sym, pos in self._positions.items():
            pos["days_open"] += 1
            daily_theta = pos["premium_rcvd"] * 0.02   # ~2% of premium per day simplified
            theta_total += daily_theta
            # Close if profit target hit (50% of max profit)
            if pos.get("unrealised_gain", 0) >= 0.5 * pos["max_profit"]:
                theta_total += pos["premium_rcvd"] * 0.5
        self._equity += theta_total
        return theta_total

    # ─────────────────────────────────────────────────────────
    # Observation builder
    # ─────────────────────────────────────────────────────────
    def _get_obs(self) -> np.ndarray:
        if not self._episode_data:
            return np.zeros(OBS_DIM, dtype=np.float32)
        day_data = self._episode_data[min(self._day, len(self._episode_data) - 1)]

        obs = []
        # Account state
        obs += [
            self._equity / STARTING_CAPITAL - 1.0,
            self._daily_pnl / STARTING_CAPITAL,
            len(self._positions) / SETTINGS.max_open_positions,
            0.0,   # portfolio delta placeholder
        ]
        # Symbol features
        for sym in SETTINGS.trading_universe:
            feats = day_data.get(sym, {}).get("features", [0.0] * FEATURE_DIM)
            obs += feats[:FEATURE_DIM]
        # Regime (placeholder one-hot until Transformer is trained)
        obs += [1.0, 0.0, 0.0, 0.0]
        # Option chain
        for sym in SETTINGS.trading_universe:
            d = day_data.get(sym, {})
            obs += [d.get("iv", 0.2), d.get("iv_rank", 50) / 100, d.get("bid_ask", 0.05)]
        # Position flags
        for sym in SETTINGS.trading_universe:
            if sym not in self._positions:
                obs.append(0.0)
            elif self._positions[sym]["type"] == "CSP":
                obs.append(1.0)
            else:
                obs.append(2.0)

        arr = np.array(obs, dtype=np.float32)
        # Clip and zero-fill to exact OBS_DIM
        arr = arr[:OBS_DIM]
        if len(arr) < OBS_DIM:
            arr = np.pad(arr, (0, OBS_DIM - len(arr)))
        return arr

    def render(self) -> Optional[str]:
        s = (f"Day {self._day:3d} | Equity=${self._equity:,.0f} | "
             f"P&L={self._daily_pnl:+,.0f} | Positions={len(self._positions)}")
        if self.render_mode == "human":
            print(s)
        return s


# Compatibility alias
OptionsTradingEnv = OptionsPortfolioEnv

