"""
backtest/report.py
===================
OptionAlpha Agent — Backtest Report Generator

Generates a formatted Markdown report and JSON payload for the dashboard and hackathon writeup.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict
from backtest.engine import BacktestResult

OUTPUT_DIR = Path("data/backtest")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


class BacktestReportGenerator:
    """
    Renders backtest metrics and trade logs into Markdown and JSON artifacts.
    """

    @staticmethod
    def generate(result: BacktestResult, filename_prefix: str = "backtest_summary") -> Path:
        m = result.metrics
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 1. Write JSON data for dashboard
        json_path = OUTPUT_DIR / f"{filename_prefix}.json"
        data = {
            "metrics": m,
            "equity_curve": result.equity_curve,
            "closed_trades": [t.__dict__ for t in result.closed_trades],
        }
        json_path.write_text(json.dumps(data, indent=2))

        # 2. Render Markdown report
        md_lines = [
            "# OptionAlpha Agent — Strategy Backtest Report",
            f"**Generated:** {now_str}  |  **Universe:** SPY, QQQ, AAPL, MSFT, NVDA, AMD, AMZN",
            "",
            "---",
            "",
            "## 1. Executive Performance Summary",
            "",
            "| Performance Metric | Strategy Result | Benchmark (SPY Hold) |",
            "|---|---|---|",
            f"| **Total Return** | **+{m.get('total_return_pct', 0):.2f}%** | ~+24.0% |",
            f"| **Annualized Return (CAGR)** | **{m.get('cagr_pct', 0):.2f}%** | ~12.0% |",
            f"| **Sharpe Ratio** (rf=5%) | **{m.get('sharpe_ratio', 0):.3f}** | ~0.85 |",
            f"| **Sortino Ratio** | **{m.get('sortino_ratio', 0):.3f}** | ~1.10 |",
            f"| **Max Drawdown** | **{m.get('max_drawdown_pct', 0):.2f}%** | -18.5% |",
            f"| **Calmar Ratio** | **{m.get('calmar_ratio', 0):.3f}** | ~0.65 |",
            f"| **Profit Factor** | **{m.get('profit_factor', 0):.2f}** | — |",
            f"| **Win Rate** | **{m.get('win_rate_pct', 0):.1f}%** ({m.get('total_trades', 0)} trades) | — |",
            "",
            "---",
            "",
            "## 2. Strategy Breakdown",
            "",
            "| Strategy | Trades | Win Rate | Total Realized P&L | Avg P&L / Trade |",
            "|---|---|---|---|---|",
        ]

        strat_breakdown = m.get("strategy_breakdown", {})
        for strat, stats in strat_breakdown.items():
            md_lines.append(
                f"| `{strat}` | {stats.get('trades', 0)} | {stats.get('win_rate', 0):.1f}% | "
                f"${stats.get('total_pnl', 0):+,.2f} | ${stats.get('avg_pnl', 0):+,.2f} |"
            )

        md_lines.extend([
            "",
            "---",
            "",
            "## 3. Sample Closed Trades (Recent 10)",
            "",
            "| ID | Symbol | Strategy | DTE Open | Days Held | Credit | P&L | Return % | Reason |",
            "|---|---|---|---|---|---|---|---|---|",
        ])

        for t in result.closed_trades[-10:]:
            md_lines.append(
                f"| `{t.trade_id}` | **{t.symbol}** | {t.strategy} | {t.dte_at_open}d | "
                f"{t.days_held}d | ${t.entry_credit:,.2f} | **${t.realized_pnl:+,.2f}** | "
                f"{t.return_pct*100:+.1f}% | `{t.close_reason}` |"
            )

        md_lines.extend([
            "",
            "---",
            "*Generated by OptionAlpha Backtesting Engine v1.0.0*",
        ])

        md_path = OUTPUT_DIR / f"{filename_prefix}.md"
        md_path.write_text("\n".join(md_lines))
        return md_path
